### ISSUE TITLE
Certificate validation issue

### ISSUE THREAD

**Issue by santosomar** [datacenter/NCAplus#2]
You guys may want to check on this...

>> Issue: [B501:request_with_no_cert_validation] Requests call with verify=False disabling SSL certificate checks, security issue.
   Severity: High   Confidence: High
   Location: /NCAplus/app/apic_manager/api_apic_base.py:30
29	        try:
30	            post_response = requests.post(login_url, data=json_credentials, verify=False)
31	            auth = json.loads(post_response.text)

--------------------------------------------------
>> Issue: [B501:request_with_no_cert_validation] Requests call with verify=False disabling SSL certificate checks, security issue.
   Severity: High   Confidence: High
   Location: /NCAplus/app/apic_manager/api_apic_base.py:54
53	        call_url = self.url + MQ_API2_URL + 'troubleshoot.eptracker.json?ep=' + endpoint_dn
54	        get_response = requests.get(call_url, cookies=self.cookies, verify=False)
55	        inbounddata = get_response.json()

**Comment by sfloresk** [comment]
Hi @santosomar, hope you are well.
I apologize for the late reply, I didn't get a notification about this.
We did verify=false in the requests because APIC by default has a self signed certificated, and if you do not use that flag the request will fail due to not valid certificate.

Are this just warnings in the logs or it raising an exception?

Thank you

**Comment by sfloresk** [comment]
Since there are no responses in several days, I am going to assume that are just warnings. Feel free to open the case again if you have any questions

Cheers,
Santiago
